const Discord = require("discord.js")
module.exports = new Discord.MessageEmbed()
.setTitle("<:arrowtm:897892368311779359> | Comandos Antiraid.")
.setDescription(`\`deleteraid\`: Este comando buscará todos los residuos de un raid *(Canales y/o roles con el mismo nombre)* y los borrará para facilitar la reconstrucción del mismo.`)
.setColor("PURPLE")
.setTimestamp()
.setFooter("No olvides usar los comandos en los canales correspondientes!")