const Discord = require("discord.js")
module.exports = new Discord.MessageEmbed()
.setTitle("<:arrowtm:897892368311779359> | Comandos Antiraid.")
.setDescription(`\`deleteraid\`: This command will search for all the residues of a raid *(Channels and/or roles with the same name)* and it will erase them to facilitate the reconstruction of the same.`)
.setColor("PURPLE")
.setTimestamp()
.setFooter("Do not forget to use the commands in the corresponding channels!")