module.exports = (content) => {
    content.replace("SEND_MESSAGES", "\`Send Messages\`")
    .replace("MANAGE_MESSAGES", "\`Gestionar Mensajes\`")
    .replace("MANAGE_GUILD", "\`Gestionar Servidor\`")
    .replace("MANAGE_CHANNEL", "\`Gestionar Canales\`")
    .replace("MANAGE_ROLES", "\`Gestionar Roles\`")
    .replace("ADD_REACTIONS", "\`Agregar Reacciones\`")
    .replace("EMBED_LINKS", "\`Enviar Links\`")
    .replace("ATTACH_FILES", "\`Enviar Archivos\`")
    .replace("MENTION_EVERYONE", "\`Mencionar al Everyone\`")
    .replace("USE_EXTERNAL_EMOJIS", "\`Usar Emojis Externos\`")
    .replace("VIEW_CHANNEL", "\`Ver Canal\`")
    .replace("kICK_MEMBERS", "\`Expulsar Miembros\`")
    .replace("BAN_MEMBERS", "\`Banear Miembros\`")
    .replace("VIEW_AUDIT_LOGS", "\`Ver Registro de Auditoría\`")
    .replace("MANAGE_NICKNAMES", "\`Gestionar Apodos\`")
    .replace("MANAGE_WEBHOOKS", "\`Gestionar WebHooks\`")
    .replace("", "\`Conectar\`")
    .replace("SPEAK", "\`Hablar\`")
    .replace("VIDEO", "\`Vídeo\`")
    .replace("MUTE_MEMBERS", "\`Mutear Miembros\`")
    .replace("", "\`Ensordecer Miembros\`")
    .replace("MOVE_MEMBERS", "\`Mover Miembros\`")
    .replace("ADMINISTRATOR", "\`Administrador\`")
    .replace("", "\`Ver Insignias del Servidor\`")
    .replace("", "\`Crear Invitaciones\`")
    .replace("", "\`Cambiar Apodo\`")
    .replace("MANAGE_EMOJIS", "\`Gestionar Emojis\`")
    .replace("MANAGE_THREADS", "\`Gestionar Hilos\`")
    .replace("", "\`Leer el Historial de Mensajes\`")
}